config/routes.rb
Rails.application.routes.draw do
 
  resources :topics, only: [:index, :show]
  
  devise_for :users, path: "", path_names: { sign_in: 'login', sign_out: 'logout', sign_up: "register"}
  resources :portfolios, except: [:show]
  get 'ruby-items', to: 'portfolios#ruby'
  get '/portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'
  get '/about-me', to: 'pages#about'
  get '/contact', to: 'pages#contact'
  
  resources :blogs

  mount ActionCable.server => '/cable'
  
  
  root to: 'pages#home'


end

app/models/blog.rb
class Blog < ApplicationRecord
  enum status: { draft: 0, published: 1 }
  extend FriendlyId
  friendly_id :title, use: :slugged

  validates :title, :body, :topic_id, presence: true

  belongs_to :topic, optional: true
 
  has_many :comments, dependent: :destroy

  def self.recent 
    order("created_at DESC")
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy, :toggle_status]
  before_action :set_sidebar_topics, expect: [:update, :create, :destroy, :toggle_status]
  layout "blog"
  access all: [:show, :index], user: {except: [:destroy, :new, :create, :update, :edit, :toggle_status]}, site_admin: :all

  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.recent.page(params[:page]).per(5)
    @page_title = "My Blogs | Aurel Marishta"
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
    @blog = Blog.includes(:comments).friendly.find(params[:id])
    @comment = Comment.new
    @page_title = @blog.title

  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def toggle_status
    if @blog.draft?
      @blog.published!
    elsif @blog.published?
      @blog.draft!
    end
    redirect_to blogs_url, notice: 'Post status has been updated'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:title, :body, :topic_id)
    end

    def set_sidebar_topics
      @side_bar_topics = Topic.with_blogs
    end
end

app/helpers/blogs_helper.rb
module BlogsHelper

  def gravatar_helper(user)
    image_tag "https://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(user.email)}", width: 60
  end


  class CodeRayify < Redcarpet::Render::HTML
    def block_code(code, language)
      CodeRay.scan(code, language).div
    end
  end

  def markdown(text)
    coderayified = CodeRayify.new(filter_html: true, hard_wrap: true)

    options = {
      fenced_code_blocks: true,
      no_intra_emphasis: true,
      autolink: true,
      lax_html_blocks: true,
    }

    markdown_to_html = Redcarpet::Markdown.new(coderayified, options)
    markdown_to_html.render(text).html_safe
  end
end

app/views/blogs/_blog.html.erb
  <div class="blog-post">
    <h2 class="blog-post-title"><%= link_to blog.title, blog %></h2>
    <p class="blog-post-meta">Published <%= distance_of_time_in_words(blog.created_at, Time.now) %> ago</p>

    <% if logged_in?(:site_admin) %>
      <p class="blog-post-meta">
          <%# toggle_status_blog_path(blog) %>
         <%= link_to blog.status %> / 
         <%= link_to 'Edit', edit_blog_path(blog) %> / 
         <%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' }%>
      </p>
    <% end %>
    
    <p><%= markdown(blog.body) %></p>

    </div><!-- /.blog-post -->


 

app/views/blogs/_form.html.erb
<%= form_for(blog) do |form| %>
  <% if blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :topic_id %>
    <%= form.collection_select(:topic_id, Topic.all, :id, :title, 
                                {
                                  # selected: blog.topic.id,
                                  include_blank: true
                                }, 
                                  class: 'form-control'
                              )
    %>
  </div>

  <div class="form-group">
    <%= form.label :body %>
    <%= form.text_area :body, class: 'form-control', rows: 20 %>
  </div>

  <div class="form-group">
    <%= form.submit "Submit", class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<div class="col-md-8 blog-main">

  <h2>Editing Blog</h2>

  <%= render 'form', blog: @blog %>

  <%= link_to 'Show', @blog %> |
  <%= link_to 'Back', blogs_path %>

</div>

app/views/blogs/index.html.erb
<div class="col-md-8 blog-main">
  <%= paginate @blogs %>
  <%= render @blogs %>
  <%= paginate @blogs %>
  
  <%# <nav class="blog-pagination">
    <a class="btn btn-outline-primary" href="#">Older</a>
    <a class="btn btn-outline-secondary disabled" href="#">Newer</a>
  </nav> %>

</div><!-- /.blog-main -->

app/views/blogs/new.html.erb
<div class="col-md-8 blog-main">
  <h2>New Blog</h2>

  <%= render 'form', blog: @blog %>

  <%= link_to 'Back', blogs_path %>
</div>

app/views/blogs/show.html.erb
<div class="col-md-8 blog-main">
  <h2> <%= @blog.title %></h2>

  <%# <%= @blog.topic.title %> 
 
  <ul class="breadcrumb">
    <%= link_to "Home", root_path, class: "breadcrumb-item"%>
    <%= link_to @blog.topic.title, topic_path(@blog.topic), class: "breadcrumb-item"%>
    <span class="breadcrumb-item active"><%= @blog.title %></span>
</ul>
  
  <%= link_to 'Edit', edit_blog_path(@blog) if logged_in?(:site_admin)  %> | 
  <%= link_to 'Back', blogs_path %>
  
  <p><%= markdown(@blog.body) %></p>

  <!-- start of comment form -->
  <% unless current_user.is_a?(GuestUser) %>
    <%= form_for @comment, url: '#' do |f| %>
      <div class="form-group">
        <%= f.label :content %>
        <%= f.text_area :content, class: 'form-control' %>
      </div>
      <%= f.submit "Post Comment", class: "btn btn-primary" %>
    <% end %>
  <% end %>
  <!-- end of comment form -->

  <!-- start of comments -->
  <div id="comments" data-blog-id="<%= @blog.id %>">
    <%= render @blog.comments %>
  </div>
  <!-- end of comments -->


</div><!-- /.blog-main -->