config/routes.rb
Rails.application.routes.draw do
 
  resources :topics, only: [:index, :show]
  
  devise_for :users, path: "", path_names: { sign_in: 'login', sign_out: 'logout', sign_up: "register"}
  resources :portfolios, except: [:show]
  get 'ruby-items', to: 'portfolios#ruby'
  get '/portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'
  get '/about-me', to: 'pages#about'
  get '/contact', to: 'pages#contact'
  
  resources :blogs

  mount ActionCable.server => '/cable'
  
  
  root to: 'pages#home'


end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
  has_many :technologies, dependent: :destroy
  accepts_nested_attributes_for :technologies, 
                                allow_destroy: true,
                                reject_if: lambda { |attrs| attrs['name'].blank? }
  
  validates :title, :body, presence: true

  # mount_uploader :thumb_image, PortfolioUploader
  # mount_uploader :main_image, PortfolioUploader
  
  
  scope :ruby_on_rails_portfolio_items, -> { where(subtitle: "Ruby on Rails")}

end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  layout 'portfolio'
  access all: [:show, :index, :ruby], user: {except: [:destroy, :new, :create, :update, :edit]}, site_admin: :all

  def index 
    @portfolio_items = Portfolio.all
  end

  def ruby
    @ruby_portfolio_items = Portfolio.ruby_on_rails_portfolio_items
  end

  def new 
    @portfolio_item = Portfolio.new
  end

  def create
    @portfolio_item = Portfolio.new(portfolio_params)
    if @portfolio_item.valid?
      @portfolio_item.save
      redirect_to portfolios_path
    else  
      render :new
    end
  end
  
  def show 
    @portfolio_item = Portfolio.find(params[:id])
  end

  def edit 
    @portfolio_item = Portfolio.find(params[:id])
  end

  def update 
    @portfolio_item = Portfolio.find(params[:id])
    @portfolio_item.update(portfolio_params)
    if @portfolio_item.save 
      redirect_to portfolios_path
    else 
      render :edit
    end
  end 

  def destroy 
    @portfolio_item = Portfolio.find(params[:id])
    @portfolio_item.destroy
    redirect_to portfolios_path
  end

  private

  def portfolio_params
    params.require(:portfolio).permit(:title, :subtitle, :body, :main_image, :thumb_image, :url_link, :source_url, :youtube_url, technologies_attributes: [:id, :name, :_destroy])
  end



end

app/helpers/portfolios_helper.rb
module PortfoliosHelper

  def image_generator(height:, width:)
    "http://placehold.it/#{height}x#{width}" 
  end

  def portfolio_img(img,type)
  
    if img.model.main_image? || img.model.thumb_image?
      img 
    elsif type === 'thumb'
      image_generator(height: '350', width: '200')
    else  
      image_generator(height: '600', width: '400')
    end
  end
end

app/views/portfolios/_form.html.erb
<%= form_for(@portfolio_item) do |form| %>
  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
        <%= form.label :title %>
        <%= form.text_field :title, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= form.label :subtitle %>
        <%= form.text_field :subtitle, class: 'form-control' %>
      </div>
       <div class="form-group">
        <label class="btn btn-primary">
          Upload a main image file <%= form.file_field :main_image, style: "display:none;" %>
        </label>
      </div>
       <div class="form-group">
        <label class="btn btn-primary">
           Upload a thumb image file <%= form.file_field :thumb_image, style: "display:none;"%>
         </label>
      </div>
    </div>
    <div class="form-group">
      <%= form.label :youtube_url %>
      <%= form.text_field :youtube_url, class: 'form-control' %>
    </div>
    <div class="form-group">
        <%= form.label :url_link %>
        <%= form.text_field :url_link, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= form.label :source_url %>
      <%= form.text_field :source_url, class: 'form-control' %>
    </div>
    <div class="col-md-6">
      <div class="form-group">
        <%= form.label :body %>
        <%= form.text_area :body, class: 'form-control', rows: 15 %>
      </div>
    </div>
  </div>

  <hr>

  <div class="col-md-12">
    <h3>Technologies used</h3>
    <div>
      <%= form.fields_for :technologies do |technology_form| %>
       <%= render 'technology_fields', f: technology_form %>
      <% end %>
      <div>
        <%= link_to_add_association 'Add Technology', form, :technologies %>
      </div>
    <div>

    <div class="form-group">
      <%= form.submit 'Save Portfolio Item', class: 'btn btn-primary btn-block' %>
    </div>
  </div>
<% end %>

app/views/portfolios/_portfolio_item.html.erb
<div class="col-md-4 k">
  <div class="card mb-4 box-shadow">
    <div class="portfolio-image-box">
      <a href="<%= portfolio_show_path(portfolio_item) %>"><%= image_tag portfolio_item.thumb_image.url %></a>
    </div>
    <div class="card-body">
      <p class="card-text">
        <span><%= link_to portfolio_item.title, portfolio_show_path(portfolio_item) %></span> <%= portfolio_item.subtitle %>
      </p>
    </div>
  </div>
</div>

app/views/portfolios/_technology_fields.html.erb
<div class="form-group nested-fields">
  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control'  %>
  <%= link_to_remove_association 'Remove Technology', f %>
</div>

app/views/portfolios/edit.html.erb
<div class="container portfolio-item">
  <h1>Update Portfolio</h1>
  <%= render 'form', portfolio_item: @portfolio_item %>
</div>

app/views/portfolios/index.html.erb
<div class="album py-5 bg-light">
  <div class="container">
    <div class="row">
    <%# <%= link_to "Create New Item", new_portfolio_path if logged_in?(:site_admin)  %> 

      <%= render partial: 'portfolio_item', collection: @portfolio_items %>
    </div>
  </div>
</div>

app/views/portfolios/new.html.erb
<div class="container portfolio-item">
  <h1>Create a Portfolio</h1>
  <%= render 'form', portfolio_item: @portfolio_item %>
</div>

app/views/portfolios/ruby.html.erb
<h1>Ruby Portfolios</h1>

 <% @ruby_portfolio_items.each do |portfolio_item|%>
    <p><%= link_to portfolio_item.title, portfolio_show_path(portfolio_item) %></p>
    <p><%= portfolio_item.subtitle %></p>
    <p><%= portfolio_item.body %></p>
    <%= image_tag portfolio_item.thumb_image if !portfolio_item.thumb_image.nil? %>
    <%= link_to "Edit Portfolio", edit_portfolio_path(portfolio_item) if logged_in?(:site_admin) %>
    <%= link_to "Delete Portfolio", portfolio_path(portfolio_item), method: :delete, data: { confirm: "Are you sure?"} if logged_in?(:site_admin)  %>
  <% end %>

app/views/portfolios/show.html.erb
<div class="container portfolio-container">
  <div class="row">
    <div class="col-md-7">
      <div class="portfolio-show-image-box">
        <%= image_tag @portfolio_item.main_image.url%>
      </div>
      <div class="d-flex justify-content-between align-items-center">
        <div class="btn-group portfolio-links">
          <% if @portfolio_item.youtube_url? %>
            <a target="_blank" href="<%= @portfolio_item.youtube_url %>"><button type="button" class="btn btn btn-outline-primary portfolio-link">View Youtube Demo</button></a>
          <% end %>
          <a target="_blank" href="<%= @portfolio_item.url_link %>"><button type="button" class="btn btn btn-outline-primary portfolio-link">View Live Site</button></a>
          <% if @portfolio_item.source_url? %>
            <a target="_blank" href="<%= @portfolio_item.source_url %>"><button type="button" class="btn btn btn-outline-info portfolio-link">View Source Code</button></a>
          <% end %>
        </div>
        
      </div>
    </div>
    <div class="col-md-5">
      <h1><%= @portfolio_item.title%></h1>
      
      <hr>
      
      <em><%= @portfolio_item.subtitle %></em>
      <p><%= @portfolio_item.body%></p>
      
      <hr>
      
      <h3>Technologies Used</h3>
      <% @portfolio_item.technologies.each do |t| %>
        <p><%= t.name %></p>
      <% end %>

      <% if logged_in?(:site_admin)%>
        <div class="">
          <%= link_to "Edit Item", edit_portfolio_path(@portfolio_item), class: 'btn btn-warning' %>
          <%= link_to "Delete Portfolio", portfolio_path(@portfolio_item), method: :delete, data: { confirm: "Are you sure?"} %>
        </div>
      <% end %>

    </div>
  </div>
</div>