config/routes.rb
Rails.application.routes.draw do
 
  resources :topics, only: [:index, :show]
  
  devise_for :users, path: "", path_names: { sign_in: 'login', sign_out: 'logout', sign_up: "register"}
  resources :portfolios, except: [:show]
  get 'ruby-items', to: 'portfolios#ruby'
  get '/portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'
  get '/about-me', to: 'pages#about'
  get '/contact', to: 'pages#contact'
  
  resources :blogs

  mount ActionCable.server => '/cable'
  
  
  root to: 'pages#home'


end

app/views/shared/_application_footer.html.erb
<footer class="mastfoot mt-auto">
  <div class="inner">
    <p>	&copy; 2018 | <strong>Aurel Marishta</strong> All rights reserved </p>
  </div>
</footer>

app/views/shared/_application_nav.html.erb
<header class="masthead mb-auto">
  <div class="inner">
    <%# <h3 class="masthead-brand">Aurel Marishta</h3> %>
    <h3><%= link_to 'Aurel Marishta', root_path, class: "masthead-brand" %></h3>
    <nav class="nav nav-masthead justify-content-center app-nav">
      <%= nav_helper('nav-link', 'span') %>
      <%# <%= login_helper('nav-link') %> 
    </nav>
  </div>
</header>

app/views/shared/_blog_footer.html.erb
<footer class="blog-footer">
  <p>	&copy; 2018 | <strong>Aurel Marishta</strong> All rights reserved </p>
  <p>
    <a href="#">Back to top</a>
  </p>
</footer>

app/views/shared/_blog_header.html.erb
<div class="blog-header">
  <div class="container">
    <h1 class="blog-title">My Blog</h1>
    <p class="lead blog-description">Road to Developer</p>
    <span>
      <%= link_to "Write a New Blog", new_blog_path if logged_in?(:site_admin) %>
    </span>
    <span>

    </span>
  </div>
</div>

app/views/shared/_blog_nav.html.erb
<nav class="navbar navbar-expand-md navbar-light bg-light blog-nav">
  <div class="container">
    <%= link_to "Aurel Marishta", root_path, class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
 
    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
     <ul class="navbar-nav ml-auto">
       <%= nav_helper 'nav-link', 'span' %>
       <%= login_helper 'nav-link' %>
     </ul>
    </div>
  </div>
</nav>



 

app/views/shared/_blog_sidebar.html.erb
<aside class="col-md-4 blog-sidebar">
  <div class="p-3 mb-3 bg-light rounded">
    <h4 class="font-italic">About</h4>
    <p class="mb-0">Driven Fullstack Web Developer with a passion for music. Currently developing applications with React, Ruby on Rails, Redux, Javascript, PHP, HTML, and CSS.</p>
  </div>

  <div class="p-3">
     <h4 class='font-italic'>Topics</h4>
    <ol class="list-unstyled topic-links">
      <% @side_bar_topics.each do |topic| %>
        <li><%= link_to topic.title, topic_path(topic) %> </li>
      <% end %>
    </ol>
  </div>
  
  <div class="p-3">
    <h4 class="font-italic">Find me</h4>
    <ol class="list-unstyled social-links">
      <li><a href="https://github.com/Salsa-Dude"><%= fa_icon "github" %> </a></li>
      <li><a href="https://www.linkedin.com/in/joseph-arias-4b917775/"><%= fa_icon "linkedin" %></a></li>
      <li><a href="https://codepen.io/JoEaZy/"><%= fa_icon "codepen" %></a></li>
    </ol>
  </div>
</aside><!-- /.blog-sidebar -->

app/views/shared/_nav.html.erb
<div class="<%= location %>">
  <div><%= link_to "Home", root_path %></div>
  <div><%= link_to "About", about_me_path %></div>
  <div><%= link_to "Portfolio", portfolios_path %></div>
  <div><%= link_to "Blog", blogs_path %></div>
  <div><%= link_to "Contact", contact_path %></div>
</div>

app/views/shared/_portfolio_footer.html.erb
<footer class="text-muted">
  <div class="container">
    <p class="float-right">
      <%= link_to "View All Portfolio Items", portfolios_path %> /
      <a href="#">Back to top</a>
    </p>
     <p>&copy; 2018 | <strong>Aurel Marishta</strong> All rights reserved </p>
  </div>
</footer>

app/views/shared/_portfolio_header.html.erb
<section class="jumbotron text-center">
  <div class="container">
    <h1 class="jumbotron-heading">My Portfolio</h1>
    <%# <p class="lead text-muted">Driven developer that loves Latin Music, Dancing and Soccer (HTML, SCSS, JavaScript, Jquery, React, Ruby, Ruby on Rails, PHP, SQL and Firebase)</p> %>
  
      <%= link_to 'Find Out More About me', about_me_path, class: 'btn btn-primary'%>
      <%= link_to 'My Blog', blogs_path, class: 'btn btn-secondary'%>
    </p>
  </div>
</section>

app/views/shared/_portfolio_nav.html.erb
<div class="collapse bg-dark" id="navbarHeader">
  <div class="container">
    <div class="row">
      <div class="col-sm-8 col-md-7 py-4">
        <h4 class="text-white">About</h4>
        <p class="text-muted">I've been building things my entire life - from construction projects, plumbing repairs, to websites and web applications. It's what I enjoy doing. I now build products to help businesses deliver information as a Full Stack Developer. With experience in Ruby on Rails, JavaScript, React and Redux, I've built social platforms focused on community-empowerment, architectured web applications, and created multi page websites to help businesses deliver information.</p>
      </div>
      <div class="col-sm-4 offset-md-1 py-4">
        <h4 class="text-white">Explore</h4>
        <ul class="list-unstyled">
          <%= nav_helper('text-white', 'li') %>
          <%# <li><%= login_helper 'text-white' %></li>
        </ul>
      </div>
    </div>
  </div>
</div>
<div class="navbar navbar-dark bg-dark box-shadow">
  <div class="container d-flex justify-content-between">
    <a href="/" class="navbar-brand d-flex align-items-center">
      <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="mr-2"><path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"></path><circle cx="12" cy="13" r="4"></circle></svg>
      <strong>Aurel Marishta</strong>
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  </div>
</div>